#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _bg2pyr2_reg(void);
extern void _bg2pyr_reg(void);
extern void _bgkaCA3_reg(void);
extern void _bgka_reg(void);
extern void _borgka_BC_reg(void);
extern void _borgkaCA3_reg(void);
extern void _CaBK_reg(void);
extern void _Cagk_BC_reg(void);
extern void _catCA3_reg(void);
extern void _cat_OLM_reg(void);
extern void _ccanl_BC_reg(void);
extern void _ccanlCA3_reg(void);
extern void _ccanl_reg(void);
extern void _ccanl_OLM_reg(void);
extern void _cell_im_reg(void);
extern void _cell_lca_reg(void);
extern void _cell_nca_reg(void);
extern void _currentclamp_reg(void);
extern void _gskch_BC_reg(void);
extern void _gskchCA3_reg(void);
extern void _gskch_reg(void);
extern void _h_reg(void);
extern void _IA_OLM_reg(void);
extern void _ichan2_BC_reg(void);
extern void _ichan2CA3_reg(void);
extern void _ichan2_reg(void);
extern void _ichan2_OLM_reg(void);
extern void _Ih_OLM_reg(void);
extern void _inter2emo_reg(void);
extern void _izh_reg(void);
extern void _Lca_BC_reg(void);
extern void _LcaMigCA3_reg(void);
extern void _LcaMig_reg(void);
extern void _Lca_OLM_reg(void);
extern void _mossy_reg(void);
extern void _nca_BC_reg(void);
extern void _ncaCA3_reg(void);
extern void _nca_reg(void);
extern void _pyr2emo_reg(void);
extern void _pyr2pyr_reg(void);
extern void _sahp_OLM_reg(void);
extern void _synapse_inter2pyr_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," bg2pyr2.mod");
    fprintf(stderr," bg2pyr.mod");
    fprintf(stderr," bgkaCA3.mod");
    fprintf(stderr," bgka.mod");
    fprintf(stderr," borgka_BC.mod");
    fprintf(stderr," borgkaCA3.mod");
    fprintf(stderr," CaBK.mod");
    fprintf(stderr," Cagk_BC.mod");
    fprintf(stderr," catCA3.mod");
    fprintf(stderr," cat_OLM.mod");
    fprintf(stderr," ccanl_BC.mod");
    fprintf(stderr," ccanlCA3.mod");
    fprintf(stderr," ccanl.mod");
    fprintf(stderr," ccanl_OLM.mod");
    fprintf(stderr," cell_im.mod");
    fprintf(stderr," cell_lca.mod");
    fprintf(stderr," cell_nca.mod");
    fprintf(stderr," currentclamp.mod");
    fprintf(stderr," gskch_BC.mod");
    fprintf(stderr," gskchCA3.mod");
    fprintf(stderr," gskch.mod");
    fprintf(stderr," h.mod");
    fprintf(stderr," IA_OLM.mod");
    fprintf(stderr," ichan2_BC.mod");
    fprintf(stderr," ichan2CA3.mod");
    fprintf(stderr," ichan2.mod");
    fprintf(stderr," ichan2_OLM.mod");
    fprintf(stderr," Ih_OLM.mod");
    fprintf(stderr," inter2emo.mod");
    fprintf(stderr," izh.mod");
    fprintf(stderr," Lca_BC.mod");
    fprintf(stderr," LcaMigCA3.mod");
    fprintf(stderr," LcaMig.mod");
    fprintf(stderr," Lca_OLM.mod");
    fprintf(stderr," mossy.mod");
    fprintf(stderr," nca_BC.mod");
    fprintf(stderr," ncaCA3.mod");
    fprintf(stderr," nca.mod");
    fprintf(stderr," pyr2emo.mod");
    fprintf(stderr," pyr2pyr.mod");
    fprintf(stderr," sahp_OLM.mod");
    fprintf(stderr," synapse_inter2pyr.mod");
    fprintf(stderr," vecevent.mod");
    fprintf(stderr, "\n");
  }
  _bg2pyr2_reg();
  _bg2pyr_reg();
  _bgkaCA3_reg();
  _bgka_reg();
  _borgka_BC_reg();
  _borgkaCA3_reg();
  _CaBK_reg();
  _Cagk_BC_reg();
  _catCA3_reg();
  _cat_OLM_reg();
  _ccanl_BC_reg();
  _ccanlCA3_reg();
  _ccanl_reg();
  _ccanl_OLM_reg();
  _cell_im_reg();
  _cell_lca_reg();
  _cell_nca_reg();
  _currentclamp_reg();
  _gskch_BC_reg();
  _gskchCA3_reg();
  _gskch_reg();
  _h_reg();
  _IA_OLM_reg();
  _ichan2_BC_reg();
  _ichan2CA3_reg();
  _ichan2_reg();
  _ichan2_OLM_reg();
  _Ih_OLM_reg();
  _inter2emo_reg();
  _izh_reg();
  _Lca_BC_reg();
  _LcaMigCA3_reg();
  _LcaMig_reg();
  _Lca_OLM_reg();
  _mossy_reg();
  _nca_BC_reg();
  _ncaCA3_reg();
  _nca_reg();
  _pyr2emo_reg();
  _pyr2pyr_reg();
  _sahp_OLM_reg();
  _synapse_inter2pyr_reg();
  _vecevent_reg();
}
