#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _CaDynamics_reg();
extern void _Ca_HVA_reg();
extern void _Ca_LVA_reg();
extern void _ExpGABAab_reg();
extern void _Ih_reg();
extern void _Im_reg();
extern void _Im_v2_reg();
extern void _K_P_reg();
extern void _K_T_reg();
extern void _Kd_reg();
extern void _KdT_reg();
extern void _Kv2like_reg();
extern void _Kv3_1_reg();
extern void _Kv3_1T_reg();
extern void _MyExp2Sid_reg();
extern void _NaTa_reg();
extern void _NaTs_reg();
extern void _NaV_reg();
extern void _NaV2_reg();
extern void _SK_reg();
extern void _ca_reg();
extern void _cad_reg();
extern void _cadyn_reg();
extern void _capool_reg();
extern void _ch_CavL_reg();
extern void _ch_CavN_reg();
extern void _ch_HCN_reg();
extern void _ch_HCNolm_reg();
extern void _ch_HCNp_reg();
extern void _ch_KCaS_reg();
extern void _ch_Kdrfast_reg();
extern void _ch_Kdrfastngf_reg();
extern void _ch_Kdrp_reg();
extern void _ch_Kdrslow_reg();
extern void _ch_KvA_reg();
extern void _ch_KvAdistp_reg();
extern void _ch_KvAngf_reg();
extern void _ch_KvAolm_reg();
extern void _ch_KvAproxp_reg();
extern void _ch_KvCaB_reg();
extern void _ch_KvGroup_reg();
extern void _ch_KvM_reg();
extern void _ch_Nav_reg();
extern void _ch_Navaxonp_reg();
extern void _ch_Navbis_reg();
extern void _ch_Navcck_reg();
extern void _ch_Navngf_reg();
extern void _ch_Navp_reg();
extern void _ch_leak_reg();
extern void _gabaa_reg();
extern void _h_reg();
extern void _halfgap_reg();
extern void _iconc_Ca_reg();
extern void _kaprox_reg();
extern void _kca_reg();
extern void _kdrca1_reg();
extern void _kdrinter_reg();
extern void _kdrinter_WB_reg();
extern void _km_reg();
extern void _kv_reg();
extern void _leakinter_reg();
extern void _nainter_WB_reg();
extern void _nap_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," CaDynamics.mod");
fprintf(stderr," Ca_HVA.mod");
fprintf(stderr," Ca_LVA.mod");
fprintf(stderr," ExpGABAab.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," Im.mod");
fprintf(stderr," Im_v2.mod");
fprintf(stderr," K_P.mod");
fprintf(stderr," K_T.mod");
fprintf(stderr," Kd.mod");
fprintf(stderr," KdT.mod");
fprintf(stderr," Kv2like.mod");
fprintf(stderr," Kv3_1.mod");
fprintf(stderr," Kv3_1T.mod");
fprintf(stderr," MyExp2Sid.mod");
fprintf(stderr," NaTa.mod");
fprintf(stderr," NaTs.mod");
fprintf(stderr," NaV.mod");
fprintf(stderr," NaV2.mod");
fprintf(stderr," SK.mod");
fprintf(stderr," ca.mod");
fprintf(stderr," cad.mod");
fprintf(stderr," cadyn.mod");
fprintf(stderr," capool.mod");
fprintf(stderr," ch_CavL.mod");
fprintf(stderr," ch_CavN.mod");
fprintf(stderr," ch_HCN.mod");
fprintf(stderr," ch_HCNolm.mod");
fprintf(stderr," ch_HCNp.mod");
fprintf(stderr," ch_KCaS.mod");
fprintf(stderr," ch_Kdrfast.mod");
fprintf(stderr," ch_Kdrfastngf.mod");
fprintf(stderr," ch_Kdrp.mod");
fprintf(stderr," ch_Kdrslow.mod");
fprintf(stderr," ch_KvA.mod");
fprintf(stderr," ch_KvAdistp.mod");
fprintf(stderr," ch_KvAngf.mod");
fprintf(stderr," ch_KvAolm.mod");
fprintf(stderr," ch_KvAproxp.mod");
fprintf(stderr," ch_KvCaB.mod");
fprintf(stderr," ch_KvGroup.mod");
fprintf(stderr," ch_KvM.mod");
fprintf(stderr," ch_Nav.mod");
fprintf(stderr," ch_Navaxonp.mod");
fprintf(stderr," ch_Navbis.mod");
fprintf(stderr," ch_Navcck.mod");
fprintf(stderr," ch_Navngf.mod");
fprintf(stderr," ch_Navp.mod");
fprintf(stderr," ch_leak.mod");
fprintf(stderr," gabaa.mod");
fprintf(stderr," h.mod");
fprintf(stderr," halfgap.mod");
fprintf(stderr," iconc_Ca.mod");
fprintf(stderr," kaprox.mod");
fprintf(stderr," kca.mod");
fprintf(stderr," kdrca1.mod");
fprintf(stderr," kdrinter.mod");
fprintf(stderr," kdrinter_WB.mod");
fprintf(stderr," km.mod");
fprintf(stderr," kv.mod");
fprintf(stderr," leakinter.mod");
fprintf(stderr," nainter_WB.mod");
fprintf(stderr," nap.mod");
fprintf(stderr, "\n");
    }
_CaDynamics_reg();
_Ca_HVA_reg();
_Ca_LVA_reg();
_ExpGABAab_reg();
_Ih_reg();
_Im_reg();
_Im_v2_reg();
_K_P_reg();
_K_T_reg();
_Kd_reg();
_KdT_reg();
_Kv2like_reg();
_Kv3_1_reg();
_Kv3_1T_reg();
_MyExp2Sid_reg();
_NaTa_reg();
_NaTs_reg();
_NaV_reg();
_NaV2_reg();
_SK_reg();
_ca_reg();
_cad_reg();
_cadyn_reg();
_capool_reg();
_ch_CavL_reg();
_ch_CavN_reg();
_ch_HCN_reg();
_ch_HCNolm_reg();
_ch_HCNp_reg();
_ch_KCaS_reg();
_ch_Kdrfast_reg();
_ch_Kdrfastngf_reg();
_ch_Kdrp_reg();
_ch_Kdrslow_reg();
_ch_KvA_reg();
_ch_KvAdistp_reg();
_ch_KvAngf_reg();
_ch_KvAolm_reg();
_ch_KvAproxp_reg();
_ch_KvCaB_reg();
_ch_KvGroup_reg();
_ch_KvM_reg();
_ch_Nav_reg();
_ch_Navaxonp_reg();
_ch_Navbis_reg();
_ch_Navcck_reg();
_ch_Navngf_reg();
_ch_Navp_reg();
_ch_leak_reg();
_gabaa_reg();
_h_reg();
_halfgap_reg();
_iconc_Ca_reg();
_kaprox_reg();
_kca_reg();
_kdrca1_reg();
_kdrinter_reg();
_kdrinter_WB_reg();
_km_reg();
_kv_reg();
_leakinter_reg();
_nainter_WB_reg();
_nap_reg();
}
